version: "3"
services:
  nothification:
    build: ./
    ports:
    - "5002:5002"
    links: 
    - notificationmongo
  notificationmongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
    - nothData:/data/Nothidb

volumes:
  nothData:
